# Generated by Django 3.2.15 on 2022-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='fecha_cobro',
            field=models.DateField(),
        ),
    ]
