# Generated by Django 3.2.15 on 2022-10-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_gastos_fecha_cobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('Entretención', 'Entretención'), ('Transporte', 'Transporte'), ('Alimento', 'Alimentos'), ('Cuentas Básicas', 'Cuentas Básicas'), ('Dividendo', 'Dividendo'), ('Otros', 'Otros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='recurrente',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
    ]
