# Generated by Django 3.2.15 on 2022-10-26 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion', '0003_auto_20221010_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recurrente', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('fecha_cobro', models.DateField()),
                ('monto', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Entretención', 'Entretención'), ('Transporte', 'Transporte'), ('Alimento', 'Alimentos'), ('Cuentas Básicas', 'Cuentas Básicas'), ('Dividendo', 'Dividendo'), ('Otros', 'Otros')], max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
