# Generated by Django 3.2.15 on 2022-10-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_ingresos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresos',
            options={'ordering': ['fecha_ingreso']},
        ),
        migrations.RenameField(
            model_name='ingresos',
            old_name='fecha_cobro',
            new_name='fecha_ingreso',
        ),
    ]
