# Generated by Django 3.2.16 on 2022-11-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20221026_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='categoria',
        ),
    ]
