# Generated by Django 3.2.15 on 2022-10-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20221026_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresos',
            name='categoria',
        ),
    ]
